config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callbacks

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :ideas do
      member do
        post 'update_active_time'
      end

      collection do
        get 'search'
        get 'filter'
      end
    end

    resources :user_edits, only: [:edit, :update]
    resources :omni_registrations, only: [:create]
    resources :interests, only: [:create, :new]
    resources :sponsors, only: [:show, :edit, :update]
    resources :businessmen, only: [:show]
    root 'ideas#index'
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace 'api' do
    namespace 'v1' do
      resources :likes, only: [:create, :destroy]
      resources :dislikes, only: [:create, :destroy]
      resources :ratings, only: [:create]
      resources :autofills, only: [:create]
    end
  end
end

app/models/idea.rb
class Idea < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  extend ElasticQueries

  mapping do
    indexes :name
    indexes :description
    indexes :plan

    indexes :industries, type: :object do
      indexes :name, type: 'completion'
    end

    indexes :districts, type: :object do
      indexes :name, type: 'completion'
    end

    indexes :require_helps, type: :object do
      indexes :name, type: 'completion'
    end

    indexes :members, type: :object do
      indexes :name, type: 'completion'
    end
  end

  belongs_to :user

  has_many :local_require_helps, dependent: :destroy
  has_many :local_members, dependent: :destroy
  has_many :local_districts, dependent: :destroy
  has_many :local_industries, dependent: :destroy
  has_many :industries, through: :local_industries
  has_many :districts, through: :local_districts
  has_many :members, through: :local_members
  has_many :require_helps, through: :local_require_helps
  has_many :interests, dependent: :destroy
  has_many :views, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :ratings, dependent: :destroy

  accepts_nested_attributes_for :local_industries, allow_destroy: true
  accepts_nested_attributes_for :local_members, allow_destroy: true
  accepts_nested_attributes_for :local_districts, allow_destroy: true
  accepts_nested_attributes_for :local_require_helps, allow_destroy: true

  COUNT_WORDS_OF_PLAN = 10
  COUNT_WORDS_OF_DESCRIPTION = 10
  MAXIMUM_LENGHT_OF_CONTEXT = 1000
  MINIMUM_LENGTH_OF_NAME = 4
  MAXIMUN_LENGTH_OF_NAME = 25
  ACTIVE_TIME_PERIOD = 30
  ACTIVE_NOTIFICATION_PERIOD = 10

  validates :name, length: { minimum: MINIMUM_LENGTH_OF_NAME, maximum: MAXIMUN_LENGTH_OF_NAME }
  validates :plan, count_words: { minimum: COUNT_WORDS_OF_PLAN }
  validates :description, count_words: { minimum: COUNT_WORDS_OF_DESCRIPTION }
  validates :local_industries, presence: true
  validates :local_members, presence: true
  validates :local_districts, presence: true
  validates :local_require_helps, presence: true
  validates :plan, length: { maximum: MAXIMUM_LENGHT_OF_CONTEXT }
  validates :description, length: { maximum: MAXIMUM_LENGHT_OF_CONTEXT }

  before_create :set_active
  before_create :set_active_time

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :active_period, (lambda do
    active.where('active_time < ?', ACTIVE_TIME_PERIOD.day.ago)
  end)

  scope :notification_period, (lambda do
    active.where('active_time < ? ', (ACTIVE_TIME_PERIOD - ACTIVE_NOTIFICATION_PERIOD).day.ago,)
  end)

  def update_active_period?
    self.active_time < (ACTIVE_TIME_PERIOD - ACTIVE_NOTIFICATION_PERIOD).day.ago
  end

  def as_indexed_json(options = {})
    self.as_json(
      include: {
        industries: { only: [:name] },
        districts: { only: [:name] },
        require_helps: { only: [:name] },
        members: { only: [:name] }
      }
    )
  end

  def self.search(term, from)
    __elasticsearch__.search(full_text_search(term), from: from)
  end

  def self.suggest(term)
    __elasticsearch__.search(suggest_tags(term))
  end

  def self.filter(query, from)
    __elasticsearch__.search(query, from: from)
  end

  private

  def set_active
    self.active = true
  end

  def set_active_time
    self.active_time = Time.zone.now
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include CurrentPage
  load_and_authorize_resource

  ELASTICSEARCH_MIN_SIZE = 5

  def index
    @pagy, @ideas = pagy_array(IdeasQueries.new(current_user).find, items: 10)
  end

  def show
    @interests = @idea.interests.includes(:user)
    @local_members = @idea.local_members.includes(:member)
    ViewService.new(current_user, @idea).find_or_create
  end

  def new
    @idea = current_user.ideas.new
    @local_members = @idea.local_members.includes(:member)
  end

  def edit
    @idea = current_user.ideas.find(params[:id])
    @local_members = @idea.local_members.includes(:member)
  end

  def update
    @idea = current_user.ideas.find(params[:id])
    @local_members = @idea.local_members.includes(:member)
    if UpdateRecordService.new(@idea).update(association_params, idea_params)
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    idea = current_user.ideas.find(params[:id])
    idea.destroy!
    redirect_to ideas_path
  end

  def create
    @idea = current_user.ideas.new(idea_params.merge(association_params))
    @local_members = @idea.local_members.includes(:member)
    if @idea.save
      SendMailsToSponsorsWorker.perform_async(@idea.id)
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def update_active_time
    idea = Idea.find(params[:id])
    idea.update!(active_time: Time.zone.now, active: true)
    redirect_to idea_path(idea)
  end

  def search
    from = from_entry(params[:page])

    @ideas = Idea.search(params[:term], from)
    @pagy = Pagy.new_from_elasticsearch_rails(@ideas)

    if @ideas.size < ELASTICSEARCH_MIN_SIZE
      @pagy, @ideas = pagy_array(IdeaSearchService.new(params[:term]).order_by_created_at, items: 10)
    end

    render 'index'
  end

  def filter
    criteria_hash = params['category']

    query = FilterIdeasQueries.new(criteria_hash).elastic_query

    from = from_entry(params[:page])

    @ideas = Idea.filter(query, from)
    @pagy = Pagy.new_from_elasticsearch_rails(@ideas)

    render 'index'
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :description, :plan)
  end

  def association_params
    params.require(:idea).permit(local_industries_attributes: [:industry_id],
                                 local_districts_attributes: [:district_id],
                                 local_require_helps_attributes: [:require_help_id],
                                 local_members_attributes: [:amount, :member_id])
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def user_was_interested?(idea)
    current_user.interests.find_by(idea_id: idea.id).present?
  end

  def views_count(idea_id)
    View.where(idea_id: idea_id).count
  end

  def display_less_than_100_characters(context)
    return context if context.size < 100

    context[0...100] + '...'
  end
end

app/views/ideas/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="back-image back-image-1">
      </div>
      <div class="container">
        <div class="carousel-caption text-left">
          <h1><%= t(:find_help) %></h1>
          <p><%= t(:sign_up_businessman) %></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="back-image back-image-2">
      </div>
      <div class="container">
        <div class="carousel-caption">
          <h1><%= t(:help_businessmen) %></h1>
          <p><%= t(:sign_up_sponsor) %></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/ideas/_filter.html.erb
<div class="sorting text-center">
    <%= form_for :category, url: filter_ideas_path, method: :get do |form| %>
    <div class="row">
      <div class="col-12 col-md-6 col-lg-2">
        <%= t(:industries) %>
        <%= form.select :industries, Industry.all.map(&:name), {include_blank: true}, {class: 'custom-select'} %>
      </div>

      <div class="col-12 col-md-6 col-lg-2">
        <%= t(:districts) %>
        <%= form.select :districts, District.all.map(&:name), {include_blank: true}, {class: 'custom-select'} %>
      </div>

      <div class="col-12 col-md-6 col-lg-2">
        <%= t(:members) %>
        <%= form.select :members, Member.all.map(&:name), {include_blank: true}, {class: 'custom-select'} %>
      </div>

      <div class="col-12 col-md-6 col-lg-2">
        <%= t(:require_helps) %>
        <%= form.select :require_helps, RequireHelp.all.map(&:name), {include_blank: true}, {class: 'custom-select'} %>
      </div>

      <div class="col-12 col-md-12 col-lg-4">
        <br>
        <%= form.submit t(:filter), class: 'btn btn-outline-success btn-block' %>
      </div>
        </div>
    <% end %>
</div>

app/views/ideas/_members.html.erb
<div id="members">
  <% Member.all.each do |member| %>
    <span class="member" id=<%= "member_#{member.id}" %>>
      <%= button_tag "#{member.name}", type: 'button', class: 'btn btn-outline-secondary' %>
    </span>
  <% end %>
</div>

<div id="text_fields">
  <% @local_members.each do |local_member| %>
    <p id=<%= 'p_' + local_member.member_id.to_s  %>>
      <%= local_member.member.name %>
      <input type='text' value=<%= local_member.amount %> name='idea[local_members_attributes][][amount]' class='form-control'>
      <input type='hidden' value=<%= local_member.member_id %> name='idea[local_members_attributes][][member_id]'>
    </p>
  <% end %>
</div>

app/views/ideas/_plain_information.html.erb
<p>
  <%= form.label :name %> <br>
  <%= form.text_field :name, class: 'form-control' %>
</p>

<p>
  <%= form.label :description %> <br>
  <%= form.text_area :description, class: 'form-control' %>
</p>

<p>
  <%= form.label :plan %> <br>
  <%= form.text_area :plan, class: 'form-control' %>
</p>

app/views/ideas/_rating.html.erb
<div class="row">
  <% average_rating = RatingService.average_rating(@idea) %>
  <div class="col-md-6">
    <div class="all-stars">
      <% 5.times do |i| %>
        <% if i < average_rating.to_i %>
          <div class="rating-item average"></div>
          <% else %>
          <div class="rating-item average exclude"></div>
        <% end %>
      <% end %>
    </div>
 
    <div style="display: flex;">
      <h4><%= t(:average_rating) %>:</h4><h4 class="average-rating"><%= average_rating %></h4>
    </div>
    <div style="display: flex;">
      <h4><%= t(:count_votes) %>:</h4><h4 class="count-votes"><%= RatingService.count_votes(@idea) %></h4>
    </div>
  </div>

  <div class="col-md-6">
    <% if RatingService.can_create_rating?(current_user, @idea.id) %>
      <div class="stars">
       <%= t(:offer_attractiveness) %>:
        <div class="rating" id="attraction">
          <div class="rating-item" data-rate="1"></div>
          <div class="rating-item" data-rate="2"></div>
          <div class="rating-item" data-rate="3"></div>
          <div class="rating-item" data-rate="4"></div>
          <div class="rating-item" data-rate="5"></div>
        </div>

        <%= t(:implementation_strategy) %>:
        <div class="rating" id="strategy">
          <div class="rating-item" data-rate="1"></div>
          <div class="rating-item" data-rate="2"></div>
          <div class="rating-item" data-rate="3"></div>
          <div class="rating-item" data-rate="4"></div>
          <div class="rating-item" data-rate="5"></div>
        </div>

        <%= t(:competitiveness) %>:
        <div class="rating" id="competitiveness">
          <div class="rating-item" data-rate="1"></div>
          <div class="rating-item" data-rate="2"></div>
          <div class="rating-item" data-rate="3"></div>
          <div class="rating-item" data-rate="4"></div>
          <div class="rating-item" data-rate="5"></div>
        </div>

        <%= t(:financial_attractiveness) %>:
        <div class="rating" id="finance">
          <div class="rating-item" data-rate="1"></div>
          <div class="rating-item" data-rate="2"></div>
          <div class="rating-item" data-rate="3"></div>
          <div class="rating-item" data-rate="4"></div>
          <div class="rating-item" data-rate="5"></div>
        </div>

        <button id="create-rating" class="btn btn-outline-primary"><%= t(:share) %></button>
      </div>
    <% end %>
  </div>
</div>

app/views/ideas/_responded.html.erb
<button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#modalSponsors">
  <%= t(:sponsors) %>
</button>

<div class="modal fade" tabindex="-1" role="dialog" id="modalSponsors">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title"><%= t(:sponsors) %></h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body">
        <% interests.each do |interest| %>
          <p>
            <%= interest.user.name %>, <%= interest.user.phone %>,
            <%= link_to interest.user.email, sponsor_path(interest.user), class: 'btn btn-outline-primary' %> <br>
            <%= t(:message) %>: <%= interest.message %>
          </p>
        <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
      </div>

    </div>
  </div>
</div>

app/views/ideas/edit.html.erb
<div class="wrap-contanier">
  <div class="container">
    <%= render 'partials/error', record: @idea %>

    <%= form_for @idea do |f| %>

      <%= render  "plain_information", form: f %>

      <div class="row">
        <div class="col-md-4">
          <p>
            <%= t(:industries) %>: <br>
            <%= f.collection_select(:local_industries, Industry.all, :id, :name,
            { include_hidden: false, selected: @idea.industries.map(&:id) },
            { multiple: true, name: 'idea[local_industries_attributes][][industry_id]', class: 'custom-select' }) %>

            <%= hidden_field_tag 'idea[local_industries_attributes][][exist]', 'exist' %>
          </p>
        </div>

        <div class="col-md-4">
          <p>
            <%= t(:districts) %>: <br>
            <%= f.collection_select(:local_districts, District.all, :id, :name,
            { include_hidden: false, selected: @idea.districts.map(&:id) },
            { multiple: true, name: 'idea[local_districts_attributes][][district_id]', class: 'custom-select' }) %>

            <%= hidden_field_tag 'idea[local_districts_attributes][][exist]', 'exist' %>
          </p>
        </div>

        <div class="col-md-4">
          <p>
            <%= t(:require_helps) %>: <br>
            <%= f.collection_select(:local_require_helps, RequireHelp.all, :id, :name,
            { include_hidden: false, selected: @idea.require_helps.map(&:id) },
            { multiple: true, name: 'idea[local_require_helps_attributes][][require_help_id]', class: 'custom-select' }) %>

            <%= hidden_field_tag 'idea[local_require_helps_attributes][][exist]', 'exist' %>
          </p>
        </div>
      </div>


      <p>
        <%= t(:members) %>: <br>
        <%= render  "members"%>

        <%= hidden_field_tag 'idea[local_members_attributes][][exist]', 'exist' %>
      </p>

      <p>
        <%= f.submit t(:update), class: 'btn btn-outline-primary' %>
      </p>
    <% end %>

  </div>
</div>

app/views/ideas/index.html.erb
<%= render 'carousel' %>

<div class="container">
  <%= render 'filter' %>
  <div class="row">
    <% @ideas.each do |idea| %>
      <div class="col-md-6">
        <div class="card mb-4 shadow-sm">

          <h5 class="card-header">
            <%= link_to  idea.name, idea_path(idea.id), class: "btn btn-outline-dark" %>

            <div class="btn-group">
              <% if can?(:update, Idea) %>
                <%= link_to  t(:edit), edit_idea_path(idea.id), class: "btn btn-outline-warning"  %>
              <% end %>

              <% if can?(:destroy, Idea) %>
                <%= link_to t(:delete), idea_path(idea.id), method: :delete, data: { confirm: t(:sure) }, class: "btn btn-outline-danger"  %>
              <% end %>

            </div>
          </h5>

          <div class="card-body">

            <p class="card-text">
              <%= display_less_than_100_characters(idea.description) %>
            </p>

            <div class="text-muted">
              <%= t(:likes) %> <%= likes_count(idea.id) %> |
              <%= t(:dislikes) %> <%= dislikes_count(idea.id) %> |
              <%= t(:reviewed) %> <%= views_count(idea.id) %>
            </div>

          </div>

        </div>
      </div>
    <% end %>
  </div>

  <% if @pagy.count > 10 %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>
</div>

app/views/ideas/new.html.erb
<div class="wrap-contanier">
  <div class="container">
    <%= render 'partials/error', record: @idea %>

    <%= form_for @idea do |f| %>

      <%= render  "plain_information", form: f %>

      <div class="row">
        <div class="col-md-3">
          <p>
            <%= t(:industries) %>: <br>
            <%= f.collection_select(:local_industries, Industry.all, :id, :name, { include_hidden: false },
                { multiple: true,  name: 'idea[local_industries_attributes][][industry_id]', class: 'custom-select'}) %>
          </p>
        </div>

        <div class="col-md-3">
          <p>
            <%= t(:districts) %>: <br>
            <%= f.collection_select(:local_districts, District.all, :id, :name, { include_hidden: false },
                { multiple: true, name: 'idea[local_districts_attributes][][district_id]', class: 'custom-select'}) %>
          </p>
        </div>

        <div class="col-md-3">
          <p>
            <%= t(:require_helps) %>: <br>
            <%= f.collection_select(:local_require_helps, RequireHelp.all, :id, :name, { include_hidden: false },
                { multiple: true, name: 'idea[local_require_helps_attributes][][require_help_id]', class: 'custom-select'}) %>
          </p>
        </div>
      </div>

      <p>
        <%= t(:members) %>: <br>
        <%= render  "members" %>
      </p>

      <p>
        <%= f.submit t(:create), class: 'btn btn-outline-primary' %>
      </p>
    <% end %>

  </div>
</div>

app/views/ideas/show.html.erb
<div class="wrap-contanier">
  <div class="container">
    <%= link_to t(:back), :back, class: 'btn btn-outline-secondary' %>
    <h1>
      <%= @idea.name %>
      <div class="btn-group">

        <% if can?(:update, Idea) %>
          <%= link_to  t(:edit), edit_idea_path(@idea), class: "btn btn-outline-warning"  %>
        <% end %>

        <% if can?(:destroy, Idea) %>
          <%= link_to  t(:delete), idea_path(@idea), method: :delete, data: { confirm: t(:sure) }, class: "btn btn-outline-danger"  %>
        <% end %>

        <% if can?(:update_active_time, @idea) %>
          <%= link_to 'Increase activity time', update_active_time_idea_path(@idea),method: :post, data: { confirm: t(:sure) }, class: 'btn btn-outline-success' %>
        <% end %>

      </div>
    </h1>
    <p class="text-muted">
      <%= t(:date) %> <%= @idea.created_at.to_date %>
      <%= link_to @idea.user.name, businessman_path(@idea.user) %> <br>
      <%= t(:reviewed) %> <%= @idea.views.count %>
    </p>

    <% if can?(:create, Like) %>
      <p>
        <%= hidden_field_tag 'idea_id', "#{@idea.id}" %>

        <div class="btn-group">

          <div>
            <%= like_button(@idea) %>
          </div>

          <div>
            <%= dislike_button(@idea) %>
          </div>

        </div>        
      </p>
    <% end %>

    <%= t(:likes) %> <span id="like-count"><%= @idea.likes.count %></span> |
    <%= t(:dislikes) %> <span id="dislike-count"><%= @idea.dislikes.count %></span>

    <p>
      <h4><%= t(:description) %>:</h4>
      <%= @idea.description %> <br>
    </p>

    <div class="row">
      <div class="col-md-3">
        <h4><%= t(:industries) %>: </h4>
        <ul>
          <% @idea.industries.each do |industry| %>
            <li><%= industry.name %></li>
          <% end %>
        </ul>
      </div>

      <div class="col-md-3">
        <h4><%= t(:districts) %>:</h4>
        <ul>
          <% @idea.districts.each do |district| %>
            <li><%= district.name %></li>
          <% end %>
        </ul>
      </div>

      <div class="col-md-3">
        <h4><%= t(:members) %>:</h4>
        <ul>
          <% @local_members.each do |local_member| %>
            <li><%= local_member.member.name %> 
              <%= local_member.amount %></li>
          <% end %>
        </ul>
      </div>

      <div class="col-md-3">
        <h4><%= t(:require_helps) %>:</h4>
        <ul>
          <% @idea.require_helps.each do |need| %>
            <li><%= need.name %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <p>
      <h4><%= t(:plan) %>:</h4>
      <%= @idea.plan %> <br>
    </p>

    <div style="display: flex;">
      <h3><%= t(:responded) %>:</h3> <h3 id="responded"><%= @interests.size %></h3>
    </div>

    <% if current_user&.businessman? && (current_user&.id == @idea.user.id) %>
      <%= render 'responded', interests: @interests %>
    <% end %>

    <% if can?(:create, Interest) %>
      <% unless user_was_interested?(@idea) %>

        <div id="form-error"></div>

        <div id="new-interest">
          <%= link_to t(:can_help), new_interest_path(idea_id: @idea.id), remote: true, class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    <% end %>

    <hr>
    <%= render 'rating' %>

    <%= hidden_field_tag 'lang', I18n.locale%>
  </div>
</div>