config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callbacks

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :ideas do
      member do
        post 'update_active_time'
      end

      collection do
        get 'search'
        get 'filter'
      end
    end

    resources :user_edits, only: [:edit, :update]
    resources :omni_registrations, only: [:create]
    resources :interests, only: [:create, :new]
    resources :sponsors, only: [:show, :edit, :update]
    resources :businessmen, only: [:show]
    root 'ideas#index'
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace 'api' do
    namespace 'v1' do
      resources :likes, only: [:create, :destroy]
      resources :dislikes, only: [:create, :destroy]
      resources :ratings, only: [:create]
      resources :autofills, only: [:create]
    end
  end
end

app/controllers/user_edits_controller.rb
class UserEditsController < ApplicationController
  load_and_authorize_resource :user, parent: false

  def update
    I18n.locale = params[:user][:locale]
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to sponsor_path(id: @user.id, locale: @user.locale) if @user.sponsor?

      redirect_to businessman_path(id: @user.id, locale: @user.locale) if @user.businessman?
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :locale, :avatar, :age)
  end
end

app/views/user_edits/edit.html.erb
<div class="wrap-contanier">
  <div class="container">

    <%= form_for @user, url: user_edit_path(id: @user.id) do |f| %>
      <%= render 'partials/error', record: @user %>

      <div class="field">
        <%= f.label :name %> <br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :locale %> <br>
        <%= f.select :locale, I18n.available_locales, {}, {class: "custom-select mr-sm-2"} %>
      </div>

      <div class="field">
        <%= f.label :phone %> <br>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :age %> <br>
        <%= f.text_field :age, class: 'form-control' %>
      </div>

    <br>

    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-small btn-primary btn-inverse" id="browseBtn"><%= t(:browse) %></span>
        <%= f.file_field :avatar, id: 'fileField', style: "display: none;", accept: 'image/png,image/gif,image/jpeg' %>
      </span>
      <span class="form-control"></span>
    </div>

      <br>

      <div class="actions">
        <%= f.submit t(:update), class: 'btn btn-outline-success' %>
      </div>

    <% end %>

    <br>

    <% if @user.provider.nil? %>
      <%= link_to t(:edit_password), edit_user_registration_path, class: 'btn btn-outline-primary' %>
    <% end %>

    <hr>

    <h3><%= t('devise.registrations.edit.cancel_my_account') %></h3>



    <p><%= button_to t('devise.registrations.edit.cancel_my_account'), registration_path(@user), data: { confirm: t(:sure) }, method: :delete, class: 'btn btn-outline-danger' %></p>
  </div>
</div>