config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callbacks

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :ideas do
      member do
        post 'update_active_time'
      end

      collection do
        get 'search'
        get 'filter'
      end
    end

    resources :user_edits, only: [:edit, :update]
    resources :omni_registrations, only: [:create]
    resources :interests, only: [:create, :new]
    resources :sponsors, only: [:show, :edit, :update]
    resources :businessmen, only: [:show]
    root 'ideas#index'
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace 'api' do
    namespace 'v1' do
      resources :likes, only: [:create, :destroy]
      resources :dislikes, only: [:create, :destroy]
      resources :ratings, only: [:create]
      resources :autofills, only: [:create]
    end
  end
end

app/controllers/businessmen_controller.rb
class BusinessmenController < ApplicationController
  load_and_authorize_resource :user, parent: false

  def show
    @pagy, @ideas = pagy(@user.ideas.includes(:interests), items: 5)
  end
end

app/views/businessmen/_ideas.html.erb
<% if current_user&.id == @user.id %>
  <% @ideas.order(created_at: :desc).each do |idea| %>
    <hr>
    <p>
      <%= link_to idea.name, idea_path(idea), class: 'btn btn-outline-secondary' %>
      <%= link_to t(:edit), edit_idea_path(idea), class: 'btn btn-outline-warning' %>
      <%= link_to t(:delete), idea_path(idea), method: :delete, data: { confirm: t(:sure) }, class: 'btn btn-outline-danger' %>

      <p class="text-muted">
        <%= t(:date) %>:  <%= idea.created_at.to_date %>
      </p>

      <p>
        <%= t(:description) %>: <br>
        <%= idea.description %>
      </p>
    </p>

    <p>
      <%= t(:reviewed) %>: <%= idea.views.count %> |
      <%= t(:likes) %>: <%= idea.likes.count %> |
      <%= t(:dislikes) %>: <%= idea.dislikes.count %> |
      <%= t(:average_rating) %>: <%= RatingService.average_rating(idea) %> |
      <%= t(:count_votes) %>: <%= RatingService.count_votes(idea) %>
    </p>

    <ul>
      <% idea.interests.each do |interest| %>
        <li>
          <p>
            <%= link_to interest.user.email, sponsor_path(interest.user) %>
            <%= t(:message) %>: <%= interest.message %>
          </p>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if @pagy.count > 5 %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>
<% end %>

app/views/businessmen/show.html.erb
<div class="wrap-contanier">
  <div class="container">

    <%= render 'users/show', user: @user %>

    <hr>

    <h1>
      <%= t(:ideas) %>:
      <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#modalIdeas">
        <%= t(:look) %>
      </button>
    </h1>

    <%= render 'ideas' %>

  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modalIdeas">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title"><%= t(:ideas) %></h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

      </div>

      <div class="modal-body">
        <% @user.ideas.each do |idea| %>
          <% if can?(:read, idea) %>
            <h2><%= link_to idea.name, idea_path(idea), class: 'btn btn-outline-primary' %></h2>
          <% end %>
        <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(:close) %></button>
      </div>

    </div>
  </div>
</div>