config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: { registrations: 'users/registrations' }, skip: :omniauth_callbacks

    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    resources :ideas do
      member do
        post 'update_active_time'
      end

      collection do
        get 'search'
        get 'filter'
      end
    end

    resources :user_edits, only: [:edit, :update]
    resources :omni_registrations, only: [:create]
    resources :interests, only: [:create, :new]
    resources :sponsors, only: [:show, :edit, :update]
    resources :businessmen, only: [:show]
    root 'ideas#index'
  end

  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace 'api' do
    namespace 'v1' do
      resources :likes, only: [:create, :destroy]
      resources :dislikes, only: [:create, :destroy]
      resources :ratings, only: [:create]
      resources :autofills, only: [:create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sponsors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all'%>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <%= link_to t(:home), ideas_path, class: 'btn btn-outline-light' %>

          <% if user_signed_in? %>
            <% if current_user.sponsor? %>
              <li class="nav-item active"><%= link_to t(:page), sponsor_path(current_user), class: "nav-link" %></li>
            <% else %>
              <li class="nav-item active"><%= link_to t(:page), businessman_path(current_user), class: "nav-link" %></li>
              <li class="nav-item active"><%= link_to t(:create_idea), new_idea_path, class: 'nav-link' %></li>
            <% end %>
              <li class="nav-item"><%= link_to t(:log_out), destroy_user_session_path, method: :delete, data: { confirm: t(:sign_out) }, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item active"><%= link_to t(:sign_in), new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item active"><%= link_to t(:sign_up), new_user_registration_path, class: "nav-link" %></li>
            <% if params[:locale].nil? or params[:locale] == 'ru' %>
              <li class="nav-item"><%= link_to 'En', root_path(locale: 'en'), class: 'nav-link' %></li>
            <% else %>
              <li class="nav-item"><%= link_to 'Ru', root_path(locale: 'ru'), class: 'nav-link' %></li>
            <% end %>
          <% end %>

        </ul>

        <%= form_for :term, url: search_ideas_path, method: :get, html: { class: "form-inline my-2 my-lg-0" } do |form| %>
          <%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2', id: 'search', autocomplete: 'off', list: 'autofill', placeholder: t(:search) %>
          <%= form.submit t(:search), class: 'btn btn-outline-success my-2 my-sm-0' %>
        <% end %>

        <datalist id="autofill"></datalist>

      </div>
    </nav>

    <div class="content">
      <% if flash[:notice] || flash[:alert] %>
        <div class="flash-div">
          <span class="notice"><%= notice %></span>
          <span class="alert"><%= alert %></span>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>